[package]
name = "libotap"
version = "0.1.0"
description = "REST API Client library for Open Build Service."
edition = "2021"
authors = [
  "Soc Virnyl Estela <contact@uncomfyhalomacro.pl>"
]
license = "MPL-2.0"
homepage = "https://codeberg.org/uncomfyhalomacro/otap"
repository = "https://codeberg.org/uncomfyhalomacro/otap"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quick-xml = { version = "0.30", features = ["overlapped-lists", "serialize"] }
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"
serde = { version = ">=1.0.184", features = ["derive", "alloc"] }
tokio = { version = "1", features = ["full"] }
url = { version = "2.4", features = ["serde"] }
