matrix:
  ARCH:
    - linux/amd64

labels:
  platform: ${ARCH}

steps:
  license:
    when:
      event: [push, tag, pull_request]
      branch: main
    image: opensuse/tumbleweed:latest
    commands:
      - zypper --non-interactive install reuse
      - just license-lint

runs_on: [ success, failure ]
